from typing import Any

def variants() -> list[str]: ...
def set_option(name: str, value: Any) -> None: ...
def start_fen(variant: str) -> str: ...
def legal_moves(variant: str, fen: str, movelist: list[str], chess960: bool = False) -> list[str]: ...
def get_fen(
    variant: str,
    fen: str,
    movelist: list[str],
    chess960: bool = False,
    sfen: bool = False,
    show_promoted: bool = False,
    count_started: int = 0,
) -> str: ...
def get_san(variant: str, fen: str, move: str, chess960: bool = False, notation: int = 0) -> str: ...
